---
#Main installation actions
#https://clickhouse.com/docs/en/getting-started/#installation
- name: Check if Vector repo is added
  become: true
  ansible.builtin.shell: "apt-cache policy | grep -i vector"
  register: vector_repo_exists
  ignore_errors: true
  changed_when: false

- name: Install by APT | Package installation
  apt:
    name: "curl"
    #state: "latest"
    update_cache: true
  become: true
  tags: [install]


- name: Add Vector repo
  become: true
  ansible.builtin.shell: bash -c "$(curl -L https://setup.vector.dev)"
  when: vector_repo_exists.rc != 0
  register: update_repo
  tags: [install]

- name: Install by APT | Package installation
  apt:
    name: "vector"
    #state: "latest"
    update_cache: true
  become: true
  tags: [install]

- name: Vector | Create Vector service
  become: true
  ansible.builtin.template:
    src: vector.service.j2
    dest: /etc/systemd/system/vector.service
    mode: '0644'  
- name: Deploy Vector configuration
  become: true
  ansible.builtin.template:
    src: templates/vector.yml.j2
    dest: /etc/vector/vector.yml
    mode: "0644"              
  notify:
    - Start Vector manually

