---
- name: Start vector service
  become: true
  ansible.builtin.systemd:
    name: vector
    state: started
    daemon_reload: true


- name: Start Vector manually
  become: true
  ansible.builtin.command: "/usr/bin/vector --config /etc/vector/vector.yml"
  async: 10
  poll: 0

 