---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  #- name: centos7
  #  image: docker.io/pycontribs/centos:7
  #  pre_build_image: true
  #  privileged: true
  #  command: "/usr/sbin/init"
  #  docker_host: "unix:///var/run/docker.sock"
  - name: ubuntu
    image: docker.io/ubuntu/python:3.12-24.04_stable
    pre_build_image: true  
    privileged: true
  # docker_host: "unix:///var/run/docker.sock"
provisioner:
  name: ansible
verifier:
  name: ansible
#scenario:
#  test_sequence:
#     - destroy
#     - create
#     - converge
#     - destroy  
